-- MySQL Script generated by MySQL Workbench
-- Thu Nov 28 09:41:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema posto_de_gasolina
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema posto_de_gasolina
-- -----------------------------------------------------
USE `posto_de_gasolina` ;

-- -----------------------------------------------------
-- Table `posto_de_gasolina`.`gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posto_de_gasolina`.`gerente` (
  `idgerente` INT(50) NOT NULL AUTO_INCREMENT,
  `nome_gerente` VARCHAR(255) NOT NULL,
  `cpf_gerente` VARCHAR(255) NOT NULL,
  `senha_gerente` VARCHAR(255) NOT NULL,
  `status_gerente` INT NOT NULL,
  PRIMARY KEY (`idgerente`),
  UNIQUE INDEX `idgerente_UNIQUE` (`idgerente` ASC) ,
  UNIQUE INDEX `cpf_gerente_UNIQUE` (`cpf_gerente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posto_de_gasolina`.`escala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posto_de_gasolina`.`escala` (
  `idescala` INT(50) NOT NULL AUTO_INCREMENT,
  `hora_inicio` TIME NOT NULL,
  `hora_fim` TIME NOT NULL,
  `gerente_idgerente` INT NOT NULL,
  PRIMARY KEY (`idescala`, `gerente_idgerente`),
  INDEX `fk_escala_gerente_idx` (`gerente_idgerente` ASC),
  CONSTRAINT `fk_escala_gerente`
    FOREIGN KEY (`gerente_idgerente`)
    REFERENCES `posto_de_gasolina`.`gerente` (`idgerente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posto_de_gasolina`.`frentista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posto_de_gasolina`.`frentista` (
  `idfrentista` INT(50) NOT NULL AUTO_INCREMENT,
  `nome_frentista` VARCHAR(255) NOT NULL,
  `cpf_frentista` VARCHAR(45) NOT NULL,
  `status_frentista` INT NOT NULL,
  `escala_idescala` INT NOT NULL,
  PRIMARY KEY (`idfrentista`, `escala_idescala`),
  UNIQUE INDEX `idfrentista_UNIQUE` (`idfrentista` ASC) ,
  INDEX `fk_frentista_escala1_idx` (`escala_idescala` ASC),
  CONSTRAINT `fk_frentista_escala1`
    FOREIGN KEY (`escala_idescala`)
    REFERENCES `posto_de_gasolina`.`escala` (`idescala`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posto_de_gasolina`.`tanque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posto_de_gasolina`.`tanque` (
  `idtanque` INT(50) NOT NULL,
  `tipo_combustivel` VARCHAR(255) NOT NULL,
  `litragem` DOUBLE NULL,
  `preco_litro` DOUBLE NOT NULL,
  PRIMARY KEY (`idtanque`),
  UNIQUE INDEX `idtanque_UNIQUE` (`idtanque` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posto_de_gasolina`.`bomba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posto_de_gasolina`.`bomba` (
  `idbomba` INT(50) NOT NULL AUTO_INCREMENT,
  `contagem_bomba` DOUBLE NULL,
  `tipocombustivel` INT(50) NOT NULL,
  PRIMARY KEY (`idbomba`, `tipocombustivel`),
  INDEX `fk_bomba_tanque1_idx` (`tipocombustivel` ASC),
  CONSTRAINT `fk_bomba_tanque1`
    FOREIGN KEY (`tipocombustivel`)
    REFERENCES `posto_de_gasolina`.`tanque` (`idtanque`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posto_de_gasolina`.`cracha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posto_de_gasolina`.`cracha` (
  `idcracha` INT(50) NOT NULL AUTO_INCREMENT,
  `frentista_idfrentista` INT NOT NULL,
  PRIMARY KEY (`idcracha`, `frentista_idfrentista`),
  INDEX `fk_cracha_frentista1_idx` (`frentista_idfrentista` ASC),
  CONSTRAINT `fk_cracha_frentista1`
    FOREIGN KEY (`frentista_idfrentista`)
    REFERENCES `posto_de_gasolina`.`frentista` (`idfrentista`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posto_de_gasolina`.`abastecer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posto_de_gasolina`.`abastecer` (
  `qtd_litros` DOUBLE NULL,
  `valor_pago` DOUBLE NOT NULL,
  `tipoCombustivel` VARCHAR(255) NOT NULL,
  `bomba_idbomba` INT(50) NOT NULL,
  `cracha_idcracha` INT(50) NOT NULL,
  `hora_abastecer` TIME NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`bomba_idbomba`, `cracha_idcracha`),
  INDEX `fk_abastecer_bomba1_idx` (`bomba_idbomba` ASC) ,
  INDEX `fk_abastecer_cracha1_idx` (`cracha_idcracha` ASC),
  CONSTRAINT `fk_abastecer_bomba1`
    FOREIGN KEY (`bomba_idbomba`)
    REFERENCES `posto_de_gasolina`.`bomba` (`idbomba`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_abastecer_cracha1`
    FOREIGN KEY (`cracha_idcracha`)
    REFERENCES `posto_de_gasolina`.`cracha` (`idcracha`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
